# build the server 
FROM node:lts-alpine as builder 
RUN apk add --no-cache libc6-compat

WORKDIR /usr/app

COPY ./package.json .
COPY ./turbo.json .
COPY ./apps/web ./apps/web
COPY ./packages/common ./packages/common

RUN yarn  install

ENV CI=true


ARG SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_S3_BUCKET_REGION
ARG AWS_S3_BUCKET
ARG CLOUDFRONT

ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
ENV SENTRY_ORG=$SENTRY_ORG
ENV SENTRY_PROJECT=$SENTRY_PROJECT
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_S3_BUCKET_REGION=$AWS_S3_BUCKET_REGION
ENV AWS_S3_BUCKET=$AWS_S3_BUCKET
ENV CLOUDFRONT=$CLOUDFRONT



RUN yarn run build:web

#################################################################

FROM node:lts-alpine
RUN apk add --no-cache libc6-compat

COPY --from=builder /usr/app/apps/web/build ./usr/app/apps/web/build
COPY --from=builder /usr/app/apps/web/public ./usr/app/apps/web/public
COPY --from=builder /usr/app/packages/common/dist ./usr/app/packages/common/dist

WORKDIR /usr/app

COPY ./package.json .
COPY ./apps/web/package.json ./apps/web/
COPY ./packages/common/package.json ./packages/common/

RUN yarn install --production

WORKDIR /usr/app/apps/web

ENV NODE_ENV=production
ENV PORT=8080


EXPOSE 8080 

CMD ["npm","run","start"]