import { registerEnumType } from '@nestjs/graphql';

export enum EventType {
  SHOPIFY_PRODUCT_SYNC = 'SHOPIFY_PRODUCT_SYNC',
  SHOPIFY_CUSTOMER_SYNC = 'SHOPIFY_CUSTOMER_SYNC',
  SHOPIFY_PRODUCT_SYNC_PROGRESS = 'SHOPIFY_PRODUCT_SYNC_PROGRESS',
  SHOPIFY_CUSTOMER_SYNC_PROGRESS = 'SHOPIFY_CUSTOMER_SYNC_PROGRESS',
  SHOPIFY = 'SHOPIFY',
  SUBSCRIBER = 'SUBSCRIBER',
  INTEGRATION = 'INTEGRATION',
  SUBSCRIBER_LIST = 'SUBSCRIBER_LIST',
  USER = 'USER',
  LIST = 'LIST',
  STORE = 'STORE',
  POST = 'POST',
  PRODUCT = 'PRODUCT',
  SIGNUP_FORM = 'SIGNUP_FORM',
  WORKFLOW = 'WORKFLOW',
  // GROWTH_STAR = 'GROWTH_STAR',
  STORE_CHALLENGE = 'STORE_CHALLENGE',
}

registerEnumType(EventType, {
  name: 'EventType',
  description: 'different types of event',
});
