blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/bespoke-surf/bespoke/discussions/categories/q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the Bespoke discussions.
  - name: Feature Request
    url: https://feedback.bespoke.surf/feature-requests
    about:
      We appreciate you taking the time to improve Bespoke with your ideas, but we
      use the Feedback canny app for this instead of the issues tab 🙂.
  - name: 💬 Bespoke Discord Channel
    url: https://discord.gg/h8gekTtq
    about: Interact with other people hosting Bespoke
  - name: 💬 New Updates (Twitter)
    url: https://twitter.com/bespoke_surf
    about: Stay up to date with Bespoke news on twitter
