export const designData = {
  counters: {
    u_column: 7,
    u_row: 7,
    u_content_heading: 2,
    u_content_text: 5,
    u_content_image: 1,
    u_content_button: 1,
    u_content_social: 1,
  },
  body: {
    id: "C-Kd2FA80o",
    rows: [
      {
        id: "KwRpPqHI7J",
        cells: [1],
        columns: [
          {
            id: "PfIphFubc_",
            contents: [
              {
                id: "2SVQA-izwo",
                type: "text",
                values: {
                  containerPadding: "50px 10px 10px",
                  anchor: "",
                  textAlign: "left",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_text_1",
                    htmlClassNames: "u_content_text",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 14px; line-height: 140%; text-align: center;"><span style="font-size: 44px; line-height: 61.6px; font-family: Oswald;"><strong>BEHEMOTH</strong></span></p>\n<p style="font-size: 14px; line-height: 140%; text-align: center;"><span style="font-size: 28px; line-height: 39.2px; font-family: Oswald;">Body &amp; Baths</span></p>',
                },
              },
            ],
            values: {
              border: {},
              padding: "0px",
              backgroundColor: "",
              _meta: {
                htmlID: "u_column_1",
                htmlClassNames: "u_column",
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: {
            htmlID: "u_row_1",
            htmlClassNames: "u_row",
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: "Q0A7OpT4Bk",
        cells: [1],
        columns: [
          {
            id: "rcotz-ohYP",
            contents: [
              {
                id: "3jnDi1zWVN",
                type: "heading",
                values: {
                  containerPadding: "50px 10px",
                  anchor: "",
                  headingType: "h1",
                  fontSize: "80px",
                  color: "#ffffff",
                  textAlign: "center",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_heading_2",
                    htmlClassNames: "u_content_heading",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: "<strong>FEELING</strong><br /><strong>LUCKY</strong>",
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: {
                htmlID: "u_column_3",
                htmlClassNames: "u_column",
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "https://images.pexels.com/photos/808510/pexels-photo-808510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            fullWidth: false,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
            width: 940,
            height: 627,
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: {
            htmlID: "u_row_3",
            htmlClassNames: "u_row",
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: "nNE8FdpxpK",
        cells: [1],
        columns: [
          {
            id: "XTlGA3NanN",
            contents: [
              {
                id: "fjk-UIBuqm",
                type: "text",
                values: {
                  containerPadding: "30px 10px",
                  anchor: "",
                  color: "#fdfdfd",
                  textAlign: "left",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_text_3",
                    htmlClassNames: "u_content_text",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 14px; line-height: 140%; text-align: center;">We made you lucky today. You received <strong>30% Off Site-Wide</strong>. Offer ends <strong>midnight this weekend</strong>. We will only publicly announce by the end of the week. Your received this message <strong>2 days early</strong>! Use code : <strong><em>#IGOTLUCKY</em></strong></p>',
                },
              },
              {
                id: "yLhl0b5QOF",
                type: "button",
                values: {
                  containerPadding: "10px 10px 50px",
                  anchor: "",
                  href: {
                    name: "web",
                    values: {
                      href: "",
                      target: "_blank",
                    },
                  },
                  buttonColors: {
                    color: "#FFFFFF",
                    backgroundColor: "#000000",
                    hoverColor: "#FFFFFF",
                    hoverBackgroundColor: "#3AAEE0",
                  },
                  size: {
                    autoWidth: true,
                    width: "100%",
                  },
                  textAlign: "center",
                  lineHeight: "120%",
                  padding: "10px 50px",
                  border: {
                    borderTopWidth: "1px",
                    borderTopStyle: "solid",
                    borderTopColor: "#ffffff",
                    borderLeftWidth: "1px",
                    borderLeftStyle: "solid",
                    borderLeftColor: "#ffffff",
                    borderRightWidth: "1px",
                    borderRightStyle: "solid",
                    borderRightColor: "#ffffff",
                    borderBottomWidth: "1px",
                    borderBottomStyle: "solid",
                    borderBottomColor: "#ffffff",
                  },
                  borderRadius: "0px",
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_button_1",
                    htmlClassNames: "u_content_button",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<span style="font-size: 20px; line-height: 24px;">SHOP NOW</span>',
                  calculatedWidth: 211,
                  calculatedHeight: 44,
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px 60px",
              border: {},
              borderRadius: "0px",
              _meta: {
                htmlID: "u_column_5",
                htmlClassNames: "u_column",
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "#000000",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: {
            htmlID: "u_row_5",
            htmlClassNames: "u_row",
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: "u0s1whj8JV",
        cells: [1],
        columns: [
          {
            id: "DgYYNoQTtx",
            contents: [
              {
                id: "sf0b_1GPzP",
                type: "text",
                values: {
                  containerPadding: "30px 10px 10px",
                  anchor: "",
                  color: "#ffffff",
                  textAlign: "left",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_text_4",
                    htmlClassNames: "u_content_text",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 14px; line-height: 140%; text-align: center;"><strong><span style="font-family: arial, helvetica, sans-serif; font-size: 14px; line-height: 19.6px;"><span style="font-size: 18px; line-height: 25.2px;">Our Socials</span></span></strong></p>',
                },
              },
              {
                id: "lOU-MOASaT",
                type: "social",
                values: {
                  containerPadding: "10px 10px 20px",
                  anchor: "",
                  icons: {
                    iconType: "circle-white",
                    icons: [
                      {
                        name: "Facebook",
                        url: "https://facebook.com/",
                      },
                      {
                        name: "Twitter",
                        url: "https://twitter.com/",
                      },
                      {
                        name: "Instagram",
                        url: "https://instagram.com/",
                      },
                    ],
                    editor: {
                      data: {
                        showDefaultIcons: true,
                        showDefaultOptions: true,
                        customIcons: [],
                        customOptions: [],
                      },
                    },
                  },
                  align: "center",
                  spacing: 5,
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_social_1",
                    htmlClassNames: "u_content_social",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: {
                htmlID: "u_column_6",
                htmlClassNames: "u_column",
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "#bebebe",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: {
            htmlID: "u_row_6",
            htmlClassNames: "u_row",
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: "6akXwDJ-iF",
        cells: [1],
        columns: [
          {
            id: "ukcHvF6eBt",
            contents: [
              {
                id: "ris5akPyiJ",
                type: "text",
                values: {
                  containerPadding: "10px",
                  anchor: "",
                  textAlign: "left",
                  lineHeight: "140%",
                  linkStyle: {
                    inherit: true,
                    linkColor: "#0000ee",
                    linkHoverColor: "#0000ee",
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: "u_content_text_5",
                    htmlClassNames: "u_content_text",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="font-size: 14px; line-height: 140%; text-align: center;"><em><span style="font-size: 10px; line-height: 14px;">No longer need these emails? <span style="text-decoration: underline; font-size: 10px; line-height: 14px;">Unsubscribe</span></span></em><br /><em><span style="font-size: 10px; line-height: 14px;">Address, State, Country, Zip code</span></em></p>',
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: {
                htmlID: "u_column_7",
                htmlClassNames: "u_column",
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: {
            htmlID: "u_row_7",
            htmlClassNames: "u_row",
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
    ],
    values: {
      popupPosition: "center",
      popupWidth: "600px",
      popupHeight: "auto",
      borderRadius: "10px",
      contentAlign: "center",
      contentVerticalAlign: "center",
      contentWidth: "500px",
      fontFamily: {
        label: "Arial",
        value: "arial,helvetica,sans-serif",
      },
      textColor: "#000000",
      popupBackgroundColor: "#FFFFFF",
      popupBackgroundImage: {
        url: "",
        fullWidth: true,
        repeat: "no-repeat",
        size: "cover",
        position: "center",
      },
      popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
      popupCloseButton_position: "top-right",
      popupCloseButton_backgroundColor: "#DDDDDD",
      popupCloseButton_iconColor: "#000000",
      popupCloseButton_borderRadius: "0px",
      popupCloseButton_margin: "0px",
      popupCloseButton_action: {
        name: "close_popup",
        attrs: {
          onClick:
            "document.querySelector('.u-popup-container').style.display = 'none';",
        },
      },
      backgroundColor: "#ffffff",
      backgroundImage: {
        url: "",
        fullWidth: true,
        repeat: "no-repeat",
        size: "custom",
        position: "center",
      },
      preheaderText: "",
      linkStyle: {
        body: true,
        linkColor: "#0000ee",
        linkHoverColor: "#0000ee",
        linkUnderline: true,
        linkHoverUnderline: true,
      },
      _meta: {
        htmlID: "u_body",
        htmlClassNames: "u_body",
      },
    },
  },
  schemaVersion: 11,
};
